### PR TITLE
Fixed #95: Impossible to override values through mapOptions

### LINKED ISSUE #95: Impossible to override values through mapOptions
In new version 0.1.15 `mapOptions` setting is presented which is great, because `mapTypeControl` was disabled by default and earlier as a workaround I had to include my own two buttons and programmatically toggle map type.

Now I tried to set `mapTypeControl` to `true` (because default Google Maps controls are enough in my case):

```js
mapOptions: {
    mapTypeControl: true
},
```

And as a result, this option was not overridden and was left with `false` value.

After some debugging I found the reason is a wrong way of using `extend`:

```js
var gmapContext = new GMapContext(this, $.extend({}, settings.mapOptions, {
    zoom: settings.zoom,
    center: new google.maps.LatLng(settings.location.latitude, settings.location.longitude),
    mapTypeId: settings.mapTypeId,
    mapTypeControl: false,
    styles: settings.styles,
    disableDoubleClickZoom: false,
    scrollwheel: settings.scrollwheel,
    streetViewControl: false,
    radius: settings.radius,
    locationName: settings.locationName,
    settings: settings,
    autocompleteOptions : settings.autocompleteOptions,
    addressFormat: settings.addressFormat,
    draggable: settings.draggable,
    markerIcon: settings.markerIcon,
    markerDraggable: settings.markerDraggable,
    markerVisible: settings.markerVisible
}));
```

The order of arguments is wrong. Must be:

```js
var gmapContext = new GMapContext(this, $.extend({}, {
    zoom: settings.zoom,
    center: new google.maps.LatLng(settings.location.latitude, settings.location.longitude),
    mapTypeId: settings.mapTypeId,
    mapTypeControl: false,
    styles: settings.styles,
    disableDoubleClickZoom: false,
    scrollwheel: settings.scrollwheel,
    streetViewControl: false,
    radius: settings.radius,
    locationName: settings.locationName,
    settings: settings,
    autocompleteOptions : settings.autocompleteOptions,
    addressFormat: settings.addressFormat,
    draggable: settings.draggable,
    markerIcon: settings.markerIcon,
    markerDraggable: settings.markerDraggable,
    markerVisible: settings.markerVisible
}, settings.mapOptions));
```

It was caused by commit https://github.com/Logicify/jquery-locationpicker-plugin/commit/3403d4360009c0e930cfb234bfeb875efdd10066.

Note that initially in #36 it was written correctly.

I'll send PR soon.

It will be great to release new version because this is definerely a bug.

### PR DESCRIPTION
**Pull request by arogachev**
Fixed #95: Impossible to override values through mapOptions

### CODE REVIEW

**Comment by kenma9123** [comment]
I was about to create a PR then I saw this. Good job :)

**Comment by Sumragen** [comment]
You are absolutely right. It will be added with next release. 
Many thanks!

**Comment by arogachev** [comment]
Why not merge it so we can at least use latest code from master (even without release) instead of copying whole js to fix that?

**Comment by arogachev** [comment]
This was fixed in https://github.com/Logicify/jquery-locationpicker-plugin/commit/a8a5c5caba21a3db2b2203475a3ba4e24565eec1. Don't know why you refused to merge this since changes are completely the same. Thanks for fixing it anyway.

**Comment by kenma9123** [comment]
They don't want traces of PRs lol.

**Pull request closed without merging**
